CREATE TABLE [dbo].[EPM$Pension Scheme] (
    [timestamp]                    ROWVERSION       NOT NULL,
    [Scheme No_]                   VARCHAR (20)     NOT NULL,
    [Scheme Name]                  VARCHAR (30)     NOT NULL,
    [Type]                         INT              NOT NULL,
    [Employee Contribution]        DECIMAL (38, 20) NOT NULL,
    [Employer Contribution]        DECIMAL (38, 20) NOT NULL,
    [Tax Relief]                   TINYINT          NOT NULL,
    [Reduce Attachable Earnings]   TINYINT          NOT NULL,
    [Employee Posting Account]     VARCHAR (20)     NOT NULL,
    [Employer Posting Account]     VARCHAR (20)     NOT NULL,
    [Provider Name]                VARCHAR (30)     NOT NULL,
    [Address]                      VARCHAR (30)     NOT NULL,
    [Address 2]                    VARCHAR (30)     NOT NULL,
    [City]                         VARCHAR (30)     NOT NULL,
    [County]                       VARCHAR (30)     NOT NULL,
    [Post Code]                    VARCHAR (20)     NOT NULL,
    [Phone No_]                    VARCHAR (30)     NOT NULL,
    [Fax No_]                      VARCHAR (30)     NOT NULL,
    [Payment Method]               INT              NOT NULL,
    [Bank Name]                    VARCHAR (30)     NOT NULL,
    [Bank Branch]                  VARCHAR (30)     NOT NULL,
    [Account Name]                 VARCHAR (30)     NOT NULL,
    [Sort Code]                    VARCHAR (8)      NOT NULL,
    [Account No_]                  VARCHAR (8)      NOT NULL,
    [BOBS_AutoPay]                 VARCHAR (6)      NOT NULL,
    [SCON No_]                     VARCHAR (9)      NOT NULL,
    [DfES Area Code]               VARCHAR (10)     NOT NULL,
    [LGPS]                         TINYINT          NOT NULL,
    [BACS Required]                TINYINT          NOT NULL,
    [Pension Type]                 INT              NOT NULL,
    [Pension Provider No_]         VARCHAR (20)     NOT NULL,
    [SchemeType]                   INT              NOT NULL,
    [AdministrativeBase]           INT              NOT NULL,
    [AutoEnrolment]                TINYINT          NOT NULL,
    [Qualifying]                   TINYINT          NOT NULL,
    [ClosedToNewEntrants]          DATETIME         NOT NULL,
    [SubjectOfSalarySacrifice]     TINYINT          NOT NULL,
    [DCContributionAgreement]      INT              NOT NULL,
    [BasedonQualifyingEarnings]    TINYINT          NOT NULL,
    [PartPaymentsAllowed]          TINYINT          NOT NULL,
    [EmployerReference]            VARCHAR (12)     NOT NULL,
    [PensionType]                  INT              NOT NULL,
    [SubmissionByWebSite]          TINYINT          NOT NULL,
    [DefaultPaymentGroup]          VARCHAR (40)     NOT NULL,
    [PaymentGroupAlt1]             VARCHAR (40)     NOT NULL,
    [PaymentGroupAlt2]             VARCHAR (40)     NOT NULL,
    [PaymentGroupAlt3]             VARCHAR (40)     NOT NULL,
    [PaymentGroupAlt4]             VARCHAR (40)     NOT NULL,
    [PaymentGroupAlt5]             VARCHAR (40)     NOT NULL,
    [PaymentGroupAlt6]             VARCHAR (40)     NOT NULL,
    [PaymentGroupAlt7]             VARCHAR (40)     NOT NULL,
    [PaymentGroupAlt8]             VARCHAR (40)     NOT NULL,
    [PaymentGroupAlt9]             VARCHAR (40)     NOT NULL,
    [DefaultPaymentSource]         VARCHAR (40)     NOT NULL,
    [PaymentSourceAlt1]            VARCHAR (40)     NOT NULL,
    [PaymentSourceAlt2]            VARCHAR (40)     NOT NULL,
    [PaymentSourceAlt3]            VARCHAR (40)     NOT NULL,
    [PaymentSourceAlt4]            VARCHAR (40)     NOT NULL,
    [PaymentSourceAlt5]            VARCHAR (40)     NOT NULL,
    [PaymentSourceAlt6]            VARCHAR (40)     NOT NULL,
    [PaymentSourceAlt7]            VARCHAR (40)     NOT NULL,
    [PaymentSourceAlt8]            VARCHAR (40)     NOT NULL,
    [PaymentSourceAlt9]            VARCHAR (40)     NOT NULL,
    [Scheme Reference]             VARCHAR (20)     NOT NULL,
    [SalSacMergePayments]          TINYINT          NOT NULL,
    [50_50 Scheme]                 TINYINT          NOT NULL,
    [TPPDates]                     TINYINT          NOT NULL,
    [NotPension]                   TINYINT          NOT NULL,
    [Added Years]                  TINYINT          NOT NULL,
    [LGPS Monthly Deficit]         DECIMAL (38, 20) NOT NULL,
    [Customer No_]                 VARCHAR (20)     NOT NULL,
    [LGPS Deficit Paid Annually]   TINYINT          NOT NULL,
    [LGPS Deficit Period (Annual)] INT              NOT NULL,
    CONSTRAINT [EPM$Pension Scheme$0] PRIMARY KEY CLUSTERED ([Scheme No_] ASC) WITH (FILLFACTOR = 98)
);

