CREATE TABLE [dbo].[EPM$Customer] (
    [timestamp]                      ROWVERSION       NOT NULL,
    [No_]                            VARCHAR (20)     NOT NULL,
    [Name]                           VARCHAR (50)     NOT NULL,
    [Search Name]                    VARCHAR (50)     NOT NULL,
    [Name 2]                         VARCHAR (50)     NOT NULL,
    [Address]                        VARCHAR (50)     NOT NULL,
    [Address 2]                      VARCHAR (50)     NOT NULL,
    [City]                           VARCHAR (30)     NOT NULL,
    [Contact]                        VARCHAR (50)     NOT NULL,
    [Phone No_]                      VARCHAR (30)     NOT NULL,
    [Telex No_]                      VARCHAR (20)     NOT NULL,
    [Our Account No_]                VARCHAR (20)     NOT NULL,
    [School DfES No_]                VARCHAR (10)     NOT NULL,
    [Global Dimension 1 Code]        VARCHAR (20)     NOT NULL,
    [Global Dimension 2 Code]        VARCHAR (20)     NOT NULL,
    [Chain Name]                     VARCHAR (10)     NOT NULL,
    [Budgeted Amount]                DECIMAL (38, 20) NOT NULL,
    [Credit Limit (LCY)]             DECIMAL (38, 20) NOT NULL,
    [Customer Posting Group]         VARCHAR (10)     NOT NULL,
    [Currency Code]                  VARCHAR (10)     NOT NULL,
    [Customer Price Group]           VARCHAR (10)     NOT NULL,
    [Language Code]                  VARCHAR (10)     NOT NULL,
    [Statistics Group]               INT              NOT NULL,
    [Payment Terms Code]             VARCHAR (10)     NOT NULL,
    [Fin_ Charge Terms Code]         VARCHAR (10)     NOT NULL,
    [Salesperson Code]               VARCHAR (10)     NOT NULL,
    [Shipment Method Code]           VARCHAR (10)     NOT NULL,
    [Shipping Agent Code]            VARCHAR (10)     NOT NULL,
    [Place of Export]                VARCHAR (20)     NOT NULL,
    [Invoice Disc_ Code]             VARCHAR (20)     NOT NULL,
    [Customer Disc_ Group]           VARCHAR (10)     NOT NULL,
    [Country_Region Code]            VARCHAR (10)     NOT NULL,
    [Collection Method]              VARCHAR (20)     NOT NULL,
    [Amount]                         DECIMAL (38, 20) NOT NULL,
    [Blocked]                        INT              NOT NULL,
    [Invoice Copies]                 INT              NOT NULL,
    [Last Statement No_]             INT              NOT NULL,
    [Print Statements]               TINYINT          NOT NULL,
    [Bill-to Customer No_]           VARCHAR (20)     NOT NULL,
    [Priority]                       INT              NOT NULL,
    [Payment Method Code]            VARCHAR (10)     NOT NULL,
    [Last Date Modified]             DATETIME         NOT NULL,
    [Application Method]             INT              NOT NULL,
    [Prices Including VAT]           TINYINT          NOT NULL,
    [Location Code]                  VARCHAR (10)     NOT NULL,
    [Fax No_]                        VARCHAR (30)     NOT NULL,
    [Telex Answer Back]              VARCHAR (20)     NOT NULL,
    [VAT Registration No_]           VARCHAR (20)     NOT NULL,
    [Combine Shipments]              TINYINT          NOT NULL,
    [Gen_ Bus_ Posting Group]        VARCHAR (10)     NOT NULL,
    [Picture]                        IMAGE            NULL,
    [Post Code]                      VARCHAR (20)     NOT NULL,
    [County]                         VARCHAR (30)     NOT NULL,
    [E-Mail]                         VARCHAR (80)     NOT NULL,
    [Home Page]                      VARCHAR (80)     NOT NULL,
    [Reminder Terms Code]            VARCHAR (10)     NOT NULL,
    [No_ Series]                     VARCHAR (10)     NOT NULL,
    [Tax Area Code]                  VARCHAR (20)     NOT NULL,
    [Tax Liable]                     TINYINT          NOT NULL,
    [VAT Bus_ Posting Group]         VARCHAR (10)     NOT NULL,
    [Reserve]                        INT              NOT NULL,
    [Block Payment Tolerance]        TINYINT          NOT NULL,
    [IC Partner Code]                VARCHAR (20)     NOT NULL,
    [Prepayment %]                   DECIMAL (38, 20) NOT NULL,
    [Primary Contact No_]            VARCHAR (20)     NOT NULL,
    [Responsibility Center]          VARCHAR (10)     NOT NULL,
    [Shipping Advice]                INT              NOT NULL,
    [Shipping Time]                  VARCHAR (32)     NOT NULL,
    [Shipping Agent Service Code]    VARCHAR (10)     NOT NULL,
    [Service Zone Code]              VARCHAR (10)     NOT NULL,
    [Allow Line Disc_]               TINYINT          NOT NULL,
    [Base Calendar Code]             VARCHAR (10)     NOT NULL,
    [Copy Sell-to Addr_ to Qte From] INT              NOT NULL,
    [Type of Supply Code]            VARCHAR (10)     NOT NULL,
    [Phase Code]                     VARCHAR (2)      NOT NULL,
    [PAYROLL REF]                    VARCHAR (5)      NOT NULL,
    [Supply Area]                    VARCHAR (10)     NOT NULL,
    [Sch_Coll]                       VARCHAR (10)     NOT NULL,
    [Hd_Pr_Wd]                       VARCHAR (10)     NOT NULL,
    [PA Code]                        VARCHAR (10)     NOT NULL,
    [CE_RC]                          VARCHAR (10)     NOT NULL,
    [Contract Start Date]            DATETIME         NOT NULL,
    [Retainers]                      INT              NOT NULL,
    [Amount per FTE]                 DECIMAL (38, 20) NOT NULL,
    [Notes]                          VARCHAR (80)     NOT NULL,
    [Prospect No_]                   VARCHAR (20)     NOT NULL,
    [PayrollClerkMth]                VARCHAR (40)     NOT NULL,
    [Contract Signature]             VARCHAR (100)    NOT NULL,
    [Total Annual Fee (ex VAT)]      DECIMAL (38, 20) NOT NULL,
    [Pilot]                          TINYINT          NOT NULL,
    [Diocese]                        VARCHAR (30)     NOT NULL,
    [DfES Area]                      VARCHAR (3)      NOT NULL,
    [DFES School]                    INT              NOT NULL,
    [Unit Total Heads]               INT              NOT NULL,
    [Unit Total Heads Date]          DATETIME         NOT NULL,
    [Head Teacher ISR]               VARCHAR (10)     NOT NULL,
    [Payroll Provider]               VARCHAR (20)     NOT NULL,
    [Payroll TelNo]                  VARCHAR (15)     NOT NULL,
    [No_ of Manuals]                 INT              NOT NULL,
    [Customer Type]                  VARCHAR (20)     NOT NULL,
    [Contract Type]                  VARCHAR (10)     NOT NULL,
    [Customer Location2]             VARCHAR (4)      NOT NULL,
    [Signatory]                      VARCHAR (40)     NOT NULL,
    [Hd Group Size]                  VARCHAR (5)      NOT NULL,
    [Police Check Required]          TINYINT          NOT NULL,
    [Head Teacher ISR Date]          DATETIME         NOT NULL,
    [Tax Reference]                  VARCHAR (15)     NOT NULL,
    [Tax District]                   VARCHAR (30)     NOT NULL,
    [Tax Office]                     VARCHAR (40)     NOT NULL,
    [Permit Number]                  VARCHAR (12)     NOT NULL,
    [Employer Code]                  VARCHAR (6)      NOT NULL,
    [ECON Number]                    VARCHAR (9)      NOT NULL,
    [IR Paying In Book Reference]    VARCHAR (17)     NOT NULL,
    [Pensions Sort Code]             VARCHAR (8)      NOT NULL,
    [Pensions Account No_]           VARCHAR (8)      NOT NULL,
    [IR Sort Code]                   VARCHAR (8)      NOT NULL,
    [IR Account No_]                 VARCHAR (8)      NOT NULL,
    [Payslip Address Format]         INT              NOT NULL,
    [Client Account]                 TINYINT          NOT NULL,
    [Payroll Administrator]          VARCHAR (20)     NOT NULL,
    [Supply List Delivery]           INT              NOT NULL,
    [Employer Pension Code]          VARCHAR (5)      NOT NULL,
    [Web ID]                         INT              NOT NULL,
    [EPM Payroll Effectivefrom Date] DATETIME         NOT NULL,
    [EPM Payroll End Date]           DATETIME         NOT NULL,
    [Monthly Fees]                   DECIMAL (38, 20) NOT NULL,
    [Account No_ Personnel]          VARCHAR (20)     NOT NULL,
    [CRB Administration Fees]        DECIMAL (38, 20) NOT NULL,
    [Head Surname]                   VARCHAR (50)     NOT NULL,
    [Head Initials]                  VARCHAR (30)     NOT NULL,
    [Head Salutation]                INT              NOT NULL,
    [Payroll Reports E-mail]         VARCHAR (80)     NOT NULL,
    [Payroll Contact Surname]        VARCHAR (50)     NOT NULL,
    [Payroll Contact Initials]       VARCHAR (30)     NOT NULL,
    [Payroll Contact Salutation]     INT              NOT NULL,
    [Annual Payroll Fee (ex VAT)]    DECIMAL (38, 20) NOT NULL,
    [Monthly Payroll Fee (ex VAT)]   DECIMAL (38, 20) NOT NULL,
    [Payroll Start Date]             DATETIME         NOT NULL,
    [Contract Notes]                 VARCHAR (100)    NOT NULL,
    [Annual Personnel Fee (ex VAT)]  DECIMAL (38, 20) NOT NULL,
    [Monthly Personnel Fee (ex VAT)] DECIMAL (38, 20) NOT NULL,
    [Authorised CRB Signatory]       VARCHAR (50)     NOT NULL,
    [Standing Order Start Date]      DATETIME         NOT NULL,
    [Contract No_ of Months]         INT              NOT NULL,
    [No_ of Retained Days]           DECIMAL (38, 20) NOT NULL,
    [Invoice Frequency]              INT              NOT NULL,
    [No_ of Payroll Employees]       INT              NOT NULL,
    [Total Annual Fee (incl VAT)]    DECIMAL (38, 20) NOT NULL,
    [Total Monthly Fee (ex VAT)]     DECIMAL (38, 20) NOT NULL,
    [Total Monthly Fee (incl VAT)]   DECIMAL (38, 20) NOT NULL,
    [Payroll Cost Per Employee]      DECIMAL (38, 20) NOT NULL,
    [Monthly Comm_ Charge (ex VAT)]  DECIMAL (38, 20) NOT NULL,
    [Annual Comm_ Charge (ex VAT)]   DECIMAL (38, 20) NOT NULL,
    [Account No_ Payroll]            VARCHAR (20)     NOT NULL,
    [Leadership Dismissals]          INT              NOT NULL,
    [Other Dismissals]               INT              NOT NULL,
    [Team Leader]                    VARCHAR (10)     NOT NULL,
    [CRB E-mail]                     VARCHAR (80)     NOT NULL,
    [TLR Group Ref]                  VARCHAR (10)     NOT NULL,
    [TSR London Allowance]           INT              NOT NULL,
    [BACS User Number]               VARCHAR (10)     NOT NULL,
    [CRB Signatory Title]            INT              NOT NULL,
    [CRB Signatory Intials]          VARCHAR (30)     NOT NULL,
    [CRB Signatory Surname]          VARCHAR (50)     NOT NULL,
    [Occ_ Health Authority]          VARCHAR (20)     NOT NULL,
    [Medical Check Not Required]     TINYINT          NOT NULL,
    [Academy Date Increment Calc]    VARCHAR (10)     NOT NULL,
    [Contract Terminated]            DATETIME         NOT NULL,
    [Contract Accepted]              DATETIME         NOT NULL,
    [PA Code 2]                      VARCHAR (10)     NOT NULL,
    [Date of Enquiry]                DATETIME         NOT NULL,
    [Terms and Conditions Sent]      DATETIME         NOT NULL,
    [Terms and Conditions Received]  DATETIME         NOT NULL,
    [Terms and Conditions Queried]   DATETIME         NOT NULL,
    [Miracle Pay]                    TINYINT          NOT NULL,
    [Pay_ Contract Months Elapsed]   INT              NOT NULL,
    [Payroll Brochure]               TINYINT          NOT NULL,
    [Portal Dev]                     TINYINT          NOT NULL,
    [Portal User]                    TINYINT          NOT NULL,
    [CRB Only]                       TINYINT          NOT NULL,
    [Liq_ Payment Terms Code]        VARCHAR (10)     NOT NULL,
    [Tolerance Report Type]          INT              NOT NULL,
    [Tolerance Report %]             DECIMAL (38, 20) NOT NULL,
    [Tolerance Report Amount]        DECIMAL (38, 20) NOT NULL,
    [Contract Contact1]              VARCHAR (30)     NOT NULL,
    [Contract Contact2]              VARCHAR (30)     NOT NULL,
    [Contract Documents]             VARCHAR (75)     NOT NULL,
    [Salary Assessment Date]         DATETIME         NOT NULL,
    [Salary Assessment Ready]        TINYINT          NOT NULL,
    [PA Code 3]                      VARCHAR (10)     NOT NULL,
    [Focus Group]                    INT              NOT NULL,
    [Teacher Part Month Code]        VARCHAR (2)      NOT NULL,
    [Support Part Month Code]        VARCHAR (2)      NOT NULL,
    [School Pay Day]                 VARCHAR (2)      NOT NULL,
    [Use First Name]                 TINYINT          NOT NULL,
    [Auto Enrolment Date]            DATETIME         NOT NULL,
    [Weekly Teaching Hours]          DECIMAL (38, 20) NOT NULL,
    [Mobility Clause]                TINYINT          NOT NULL,
    [No_ of Teachers]                DECIMAL (38, 20) NOT NULL,
    [Customer Location]              VARCHAR (3)      NOT NULL,
    [Own Headed Paper]               TINYINT          NOT NULL,
    [Unit Total Deputy]              VARCHAR (1)      NOT NULL,
    [Unit Total Deputy Date]         DATETIME         NOT NULL,
    [EPayslips Opt-In]               TINYINT          NOT NULL,
    [JE Scheme]                      INT              NOT NULL,
    [Federation Trust]               VARCHAR (20)     NOT NULL,
    [Doc Type]                       VARCHAR (10)     NOT NULL,
    [LGPS Pension Fund]              VARCHAR (30)     NOT NULL,
    [Teacher Trust Reference]        VARCHAR (7)      NOT NULL,
    [MDC On-board Date]              DATETIME         NOT NULL,
    [Apprenticeship Levy Applies]    TINYINT          NOT NULL,
    [Apprenticeship Levy Allowance]  DECIMAL (38, 20) NOT NULL,
    [Pay Appr_ Levy In April]        TINYINT          NOT NULL,
    [Payroll Manager]                VARCHAR (20)     NOT NULL,
    [Employer NI Allowance]          DECIMAL (38, 20) NOT NULL,
    [Employer NI Allowance Eligible] TINYINT          NOT NULL,
    [MDC Trust]                      TINYINT          NOT NULL,
    [Block Automatic FPS Submission] TINYINT          NOT NULL,
    [Block Automatic EPS Submission] TINYINT          NOT NULL,
    [Contract Termination Reason]    VARCHAR (10)     NOT NULL,
    CONSTRAINT [EPM$Customer$0] PRIMARY KEY CLUSTERED ([No_] ASC) WITH (FILLFACTOR = 99)
);

