CREATE TABLE [dbo].[EPM$School Employee] (
    [timestamp]                     ROWVERSION       NOT NULL,
    [No_]                           VARCHAR (20)     NOT NULL,
    [School No_]                    VARCHAR (10)     NOT NULL,
    [First Name]                    VARCHAR (30)     NOT NULL,
    [Middle Name]                   VARCHAR (30)     NOT NULL,
    [Last Name]                     VARCHAR (30)     NOT NULL,
    [Initials]                      VARCHAR (30)     NOT NULL,
    [Job Title]                     VARCHAR (50)     NOT NULL,
    [Search Name]                   VARCHAR (30)     NOT NULL,
    [Address]                       VARCHAR (50)     NOT NULL,
    [Address 2]                     VARCHAR (50)     NOT NULL,
    [City]                          VARCHAR (30)     NOT NULL,
    [Post Code]                     VARCHAR (20)     NOT NULL,
    [County]                        VARCHAR (30)     NOT NULL,
    [Phone No_]                     VARCHAR (30)     NOT NULL,
    [Mobile Phone No_]              VARCHAR (30)     NOT NULL,
    [E-Mail]                        VARCHAR (80)     NOT NULL,
    [Alt_ Address Code]             VARCHAR (10)     NOT NULL,
    [Alt_ Address Start Date]       DATETIME         NOT NULL,
    [Alt_ Address End Date]         DATETIME         NOT NULL,
    [Picture]                       IMAGE            NULL,
    [Birth Date]                    DATETIME         NOT NULL,
    [NI Number]                     VARCHAR (30)     NOT NULL,
    [Union Code]                    VARCHAR (10)     NOT NULL,
    [Union Membership No_]          VARCHAR (30)     NOT NULL,
    [Sex]                           INT              NOT NULL,
    [Country_Region Code]           VARCHAR (10)     NOT NULL,
    [Manager No_]                   VARCHAR (20)     NOT NULL,
    [Emplymt_ Contract Code]        VARCHAR (10)     NOT NULL,
    [Statistics Group Code]         VARCHAR (10)     NOT NULL,
    [Employment Date]               DATETIME         NOT NULL,
    [Status]                        INT              NOT NULL,
    [Inactive Date]                 DATETIME         NOT NULL,
    [Cause of Inactivity Code]      VARCHAR (10)     NOT NULL,
    [Termination Date]              DATETIME         NOT NULL,
    [Grounds for Term_ Code]        VARCHAR (10)     NOT NULL,
    [Global Dimension 1 Code]       VARCHAR (20)     NOT NULL,
    [Global Dimension 2 Code]       VARCHAR (20)     NOT NULL,
    [Resource No_]                  VARCHAR (20)     NOT NULL,
    [Last Date Modified]            DATETIME         NOT NULL,
    [Extension]                     VARCHAR (30)     NOT NULL,
    [Pager]                         VARCHAR (30)     NOT NULL,
    [Fax No_]                       VARCHAR (30)     NOT NULL,
    [Company E-Mail]                VARCHAR (80)     NOT NULL,
    [Title]                         VARCHAR (30)     NOT NULL,
    [Salespers__Purch_ Code]        VARCHAR (10)     NOT NULL,
    [No_ Series]                    VARCHAR (10)     NOT NULL,
    [Personal Title]                INT              NOT NULL,
    [Previous Names]                VARCHAR (30)     NOT NULL,
    [DFES No_]                      VARCHAR (8)      NOT NULL,
    [Age Range]                     VARCHAR (40)     NOT NULL,
    [KeyStage1]                     TINYINT          NOT NULL,
    [KeyStage2]                     TINYINT          NOT NULL,
    [KeyStage3]                     TINYINT          NOT NULL,
    [KeyStage4]                     TINYINT          NOT NULL,
    [KeyStage5]                     TINYINT          NOT NULL,
    [SUBJECT1]                      VARCHAR (50)     NOT NULL,
    [SUBJECT2]                      VARCHAR (50)     NOT NULL,
    [SUBJECT3]                      VARCHAR (50)     NOT NULL,
    [SUBJECT4]                      VARCHAR (50)     NOT NULL,
    [TRB_Subject3]                  VARCHAR (30)     NOT NULL,
    [Subjects]                      VARCHAR (250)    NOT NULL,
    [Superannuation Checked]        DATETIME         NOT NULL,
    [Independent School]            TINYINT          NOT NULL,
    [Long Term Cover]               TINYINT          NOT NULL,
    [One to One Tuition]            TINYINT          NOT NULL,
    [Part Time Election Date]       DATETIME         NOT NULL,
    [Opted Out of TPS]              DATETIME         NOT NULL,
    [Verification BCPP]             VARCHAR (10)     NOT NULL,
    [Home Tuition Units]            TINYINT          NOT NULL,
    [Modified By]                   VARCHAR (20)     NOT NULL,
    [MLD]                           TINYINT          NOT NULL,
    [SLD]                           TINYINT          NOT NULL,
    [EBD]                           TINYINT          NOT NULL,
    [CoursesNotatEPMnls]            VARCHAR (250)    NOT NULL,
    [WhatSupplyTeachersNeedtoKnow]  DATETIME         NOT NULL,
    [Special Schools]               VARCHAR (20)     NOT NULL,
    [Ref1 Sent]                     DATETIME         NOT NULL,
    [Ref1 Returned]                 DATETIME         NOT NULL,
    [Ref2 Sent]                     DATETIME         NOT NULL,
    [Ref2 Returned]                 DATETIME         NOT NULL,
    [Ref Reminder Sent]             DATETIME         NOT NULL,
    [Medical Check Status]          VARCHAR (10)     NOT NULL,
    [Disability]                    TINYINT          NOT NULL,
    [Medical Clear]                 DATETIME         NOT NULL,
    [Medical Notes]                 VARCHAR (80)     NOT NULL,
    [Police Clear]                  DATETIME         NOT NULL,
    [Positive Police Check]         TINYINT          NOT NULL,
    [Barred List]                   TINYINT          NOT NULL,
    [Police Check Status]           VARCHAR (10)     NOT NULL,
    [Other Constabulary]            TINYINT          NOT NULL,
    [Police Check Sent]             DATETIME         NOT NULL,
    [TR2 Sent]                      DATETIME         NOT NULL,
    [TR2 Returned]                  DATETIME         NOT NULL,
    [TR6 Sent]                      DATETIME         NOT NULL,
    [TR6 Returned]                  DATETIME         NOT NULL,
    [TR9 Sent]                      DATETIME         NOT NULL,
    [TR9 Returned]                  DATETIME         NOT NULL,
    [Scheme Guide]                  DATETIME         NOT NULL,
    [AVC]                           DATETIME         NOT NULL,
    [Part-Time Booklet]             DATETIME         NOT NULL,
    [Early Leavers]                 DATETIME         NOT NULL,
    [Payroll Number]                VARCHAR (10)     NOT NULL,
    [Re-Employ After Pension]       DATETIME         NOT NULL,
    [Transfer of Pension]           DATETIME         NOT NULL,
    [Date Retired]                  DATETIME         NOT NULL,
    [Opted out of LGPS]             DATETIME         NOT NULL,
    [EthnicOther]                   VARCHAR (25)     NOT NULL,
    [Reminder 1 Sent]               DATETIME         NOT NULL,
    [Reminder 2 Sent]               DATETIME         NOT NULL,
    [School Notified]               DATETIME         NOT NULL,
    [Nursery]                       TINYINT          NOT NULL,
    [SEN]                           TINYINT          NOT NULL,
    [Reference No_]                 VARCHAR (16)     NOT NULL,
    [Certificate Sent]              DATETIME         NOT NULL,
    [Include on Supply List]        TINYINT          NOT NULL,
    [Birth Cetificate Recieved]     DATETIME         NOT NULL,
    [Birth Cetificate Returned]     DATETIME         NOT NULL,
    [Include on Website]            TINYINT          NOT NULL,
    [Teacher Status]                VARCHAR (10)     NOT NULL,
    [Current Teacher Appointment]   VARCHAR (60)     NOT NULL,
    [Current Support Appointment]   VARCHAR (60)     NOT NULL,
    [Payment Method]                INT              NOT NULL,
    [Bank Name]                     VARCHAR (20)     NOT NULL,
    [Bank Branch]                   VARCHAR (20)     NOT NULL,
    [Account Name]                  VARCHAR (30)     NOT NULL,
    [Bank Sort Code]                VARCHAR (8)      NOT NULL,
    [Bank Account No_]              VARCHAR (8)      NOT NULL,
    [Building Society Account]      VARCHAR (20)     NOT NULL,
    [BOBS_AutoPay]                  VARCHAR (6)      NOT NULL,
    [Bank Details Last Modified]    DATETIME         NOT NULL,
    [Bank Details Modified By]      VARCHAR (20)     NOT NULL,
    [Capita Job No_]                VARCHAR (5)      NOT NULL,
    [Reception]                     TINYINT          NOT NULL,
    [Date GTC Rec_d 02_03]          DATETIME         NOT NULL,
    [GTC Paid by 02_03]             VARCHAR (50)     NOT NULL,
    [Barred List Date Check]        DATETIME         NOT NULL,
    [Work Permit Required]          TINYINT          NOT NULL,
    [WP Reference No_]              VARCHAR (30)     NOT NULL,
    [Date Expires]                  DATETIME         NOT NULL,
    [Date Leave to remain expires]  DATETIME         NOT NULL,
    [WP Notes]                      VARCHAR (50)     NOT NULL,
    [GTC Sent]                      DATETIME         NOT NULL,
    [GTC Cleared]                   DATETIME         NOT NULL,
    [Reservist]                     TINYINT          NOT NULL,
    [Date GTC Rec_d 03_04]          DATETIME         NOT NULL,
    [GTC Paid by 03_04]             VARCHAR (50)     NOT NULL,
    [Time Modified]                 DATETIME         NOT NULL,
    [Date of EFE Election]          DATETIME         NOT NULL,
    [Reason for Retirement]         INT              NOT NULL,
    [Full_Part Time Indicator]      INT              NOT NULL,
    [Type]                          INT              NOT NULL,
    [Part Time %]                   DECIMAL (38, 20) NOT NULL,
    [Weeks]                         DECIMAL (38, 20) NOT NULL,
    [Full Time Hours]               DECIMAL (38, 20) NOT NULL,
    [Primary Appointment No_]       VARCHAR (20)     NOT NULL,
    [Total Hours]                   DECIMAL (38, 20) NOT NULL,
    [As At Date]                    DATETIME         NOT NULL,
    [Appointment No_ 2]             VARCHAR (20)     NOT NULL,
    [Weeks 2]                       DECIMAL (38, 20) NOT NULL,
    [Full Time Hours 2]             DECIMAL (38, 20) NOT NULL,
    [Total Hours 2]                 DECIMAL (38, 20) NOT NULL,
    [Appointment No_ 3]             VARCHAR (20)     NOT NULL,
    [Weeks 3]                       DECIMAL (38, 20) NOT NULL,
    [Full Time Hours 3]             DECIMAL (38, 20) NOT NULL,
    [Total Hours 3]                 DECIMAL (38, 20) NOT NULL,
    [Appointment No_ 4]             VARCHAR (20)     NOT NULL,
    [Weeks 4]                       DECIMAL (38, 20) NOT NULL,
    [Full Time Hours 4]             DECIMAL (38, 20) NOT NULL,
    [Total Hours 4]                 DECIMAL (38, 20) NOT NULL,
    [GTC Discrepancy]               VARCHAR (80)     NOT NULL,
    [Right to Work in the UK]       INT              NOT NULL,
    [Year of QTS]                   INT              NOT NULL,
    [Origin Code (Prev Employment)] VARCHAR (20)     NOT NULL,
    [QTS Route Code]                VARCHAR (20)     NOT NULL,
    [Gender]                        VARCHAR (20)     NOT NULL,
    [Sexual Orientation]            VARCHAR (20)     NOT NULL,
    [Disability Code]               VARCHAR (20)     NOT NULL,
    [Religion or Belief]            VARCHAR (20)     NOT NULL,
    [Personal Relationship]         VARCHAR (20)     NOT NULL,
    CONSTRAINT [EPM$School Employee$0] PRIMARY KEY CLUSTERED ([No_] ASC, [School No_] ASC) WITH (FILLFACTOR = 97)
);

