CREATE TABLE [dbo].[EPM$Pay Element] (
    [timestamp]                     ROWVERSION       NOT NULL,
    [Code]                          SQL_VARIANT      NOT NULL,
    [Description]                   VARCHAR (30)     NOT NULL,
    [Type]                          INT              NOT NULL,
    [Tax]                           TINYINT          NOT NULL,
    [NI]                            TINYINT          NOT NULL,
    [Pension]                       TINYINT          NOT NULL,
    [Multiplier]                    DECIMAL (38, 20) NOT NULL,
    [Use Multiplier]                TINYINT          NOT NULL,
    [Default Value]                 DECIMAL (38, 20) NOT NULL,
    [Payroll Special Code]          TINYINT          NOT NULL,
    [Posting Account]               VARCHAR (20)     NOT NULL,
    [Holiday Accrual]               TINYINT          NOT NULL,
    [Overtime]                      TINYINT          NOT NULL,
    [Reset to Zero]                 TINYINT          NOT NULL,
    [Timesheet Entry]               TINYINT          NOT NULL,
    [Attachment]                    TINYINT          NOT NULL,
    [Global Dimension 1 Code]       VARCHAR (20)     NOT NULL,
    [Global Dimension 2 Code]       VARCHAR (20)     NOT NULL,
    [Back PayCalculation Required]  TINYINT          NOT NULL,
    [Export Type]                   INT              NOT NULL,
    [Deduction on Costings Report]  TINYINT          NOT NULL,
    [Data Take On Allowed]          TINYINT          NOT NULL,
    [Rent]                          TINYINT          NOT NULL,
    [Lease Cars]                    TINYINT          NOT NULL,
    [Include in TPS Calc]           TINYINT          NOT NULL,
    [Qualifying]                    TINYINT          NOT NULL,
    [TPS Pre April Tier]            TINYINT          NOT NULL,
    [LGPS 50_50 Include Pens_ Pay]  TINYINT          NOT NULL,
    [Pension 2 Pensionable]         TINYINT          NOT NULL,
    [TPS Banding Assessed]          TINYINT          NOT NULL,
    [TPS Notional Pay]              TINYINT          NOT NULL,
    [MDC Overtime]                  TINYINT          NOT NULL,
    [Include in Gender Pay (H)]     TINYINT          NOT NULL,
    [Include in Gender Pay (B)]     TINYINT          NOT NULL,
    [Exclude From MDC Calculations] TINYINT          NOT NULL,
    [Payslip Type]                  INT              NOT NULL,
    CONSTRAINT [EPM$Pay Element$0] PRIMARY KEY CLUSTERED ([Code] ASC) WITH (FILLFACTOR = 96)
);

