CREATE TABLE [dbo].[EPM$Pay Detail Line] (
    [timestamp]                 ROWVERSION       NOT NULL,
    [Employee No_]              VARCHAR (20)     NOT NULL,
    [Line No_]                  INT              NOT NULL,
    [Tax Year]                  INT              NOT NULL,
    [Period]                    INT              NOT NULL,
    [Pay Element Code]          VARCHAR (10)     NOT NULL,
    [Description]               VARCHAR (30)     NOT NULL,
    [Amount]                    DECIMAL (38, 20) NOT NULL,
    [Hours]                     DECIMAL (38, 20) NOT NULL,
    [Rate]                      DECIMAL (38, 20) NOT NULL,
    [Periods to Advance]        INT              NOT NULL,
    [Type]                      INT              NOT NULL,
    [Recurring]                 TINYINT          NOT NULL,
    [Holiday Days]              DECIMAL (38, 20) NOT NULL,
    [Payroll Special Code]      TINYINT          NOT NULL,
    [Global Dimension 1 Code]   VARCHAR (20)     NOT NULL,
    [Pay Frequency]             INT              NOT NULL,
    [Reference]                 VARCHAR (20)     NOT NULL,
    [Employer Amount]           DECIMAL (38, 20) NOT NULL,
    [Review Date]               DATETIME         NOT NULL,
    [Global Dimension 2 Code]   VARCHAR (20)     NOT NULL,
    [Open]                      TINYINT          NOT NULL,
    [Payroll Date]              DATETIME         NOT NULL,
    [Payroll Group Code]        VARCHAR (10)     NOT NULL,
    [Reset to Zero]             TINYINT          NOT NULL,
    [Leaver]                    TINYINT          NOT NULL,
    [Orig Pro Rata Amount]      DECIMAL (38, 20) NOT NULL,
    [Payment Reference]         VARCHAR (30)     NOT NULL,
    [Appointment No_]           VARCHAR (20)     NOT NULL,
    [Budget Code 1]             VARCHAR (12)     NOT NULL,
    [Budget Code 2]             VARCHAR (12)     NOT NULL,
    [Budget Code 3]             VARCHAR (12)     NOT NULL,
    [Budget Code 4]             VARCHAR (12)     NOT NULL,
    [Budget Hours 1]            DECIMAL (38, 20) NOT NULL,
    [Budget Hours 2]            DECIMAL (38, 20) NOT NULL,
    [Budget Hours 3]            DECIMAL (38, 20) NOT NULL,
    [Budget Hours 4]            DECIMAL (38, 20) NOT NULL,
    [Budget % 1]                DECIMAL (38, 20) NOT NULL,
    [Budget % 2]                DECIMAL (38, 20) NOT NULL,
    [Budget % 3]                DECIMAL (38, 20) NOT NULL,
    [Budget % 4]                DECIMAL (38, 20) NOT NULL,
    [Pension 1]                 VARCHAR (20)     NOT NULL,
    [Pension 2]                 VARCHAR (20)     NOT NULL,
    [Pension 2 Amount]          DECIMAL (38, 20) NOT NULL,
    [Original Appointment No_]  VARCHAR (20)     NOT NULL,
    [HR Employee No_]           VARCHAR (20)     NOT NULL,
    [Pensionable Pay]           DECIMAL (38, 20) NOT NULL,
    [Employer Refund Amount]    DECIMAL (38, 20) NOT NULL,
    [Relates To Period]         INT              NOT NULL,
    [Relates To Tax Year]       INT              NOT NULL,
    [Auto Pay Take On]          TINYINT          NOT NULL,
    [LGPS]                      TINYINT          NOT NULL,
    [Pension 2 Type]            INT              NOT NULL,
    [Ee Pens_ Contr_ %]         DECIMAL (38, 20) NOT NULL,
    [Pensionable Contr_ Salary] DECIMAL (38, 20) NOT NULL,
    [Allowance Indicator]       INT              NOT NULL,
    [Point Code]                VARCHAR (20)     NOT NULL,
    [Scale Code]                VARCHAR (20)     NOT NULL,
    [Upper Pay Spine]           DECIMAL (38, 20) NOT NULL,
    [Revised Ee Pens_ Contr_ %] DECIMAL (38, 20) NOT NULL,
    [Period Arrears Worked]     INT              NOT NULL,
    [Year Arrears Worked]       INT              NOT NULL,
    [Pension 3]                 VARCHAR (20)     NOT NULL,
    [Pension 3 Amount]          DECIMAL (38, 20) NOT NULL,
    [Pension 4]                 VARCHAR (20)     NOT NULL,
    [Pension 4 Amount]          DECIMAL (38, 20) NOT NULL,
    [Month of Variation]        INT              NOT NULL,
    [Year of Variation]         INT              NOT NULL,
    [Payslip Type]              INT              NOT NULL,
    [Validated]                 TINYINT          NOT NULL,
    [Days Worked]               INT              NOT NULL,
    CONSTRAINT [EPM$Pay Detail Line$0] PRIMARY KEY CLUSTERED ([Employee No_] ASC, [Line No_] ASC) WITH (FILLFACTOR = 97)
);

