CREATE TABLE [dbo].[EPM$Appointment] (
    [timestamp]                      ROWVERSION       NOT NULL,
    [No_]                            VARCHAR (20)     NOT NULL,
    [Type]                           INT              NOT NULL,
    [No_ Series]                     VARCHAR (10)     NOT NULL,
    [Customer No_]                   VARCHAR (20)     NOT NULL,
    [Employee No_]                   VARCHAR (20)     NOT NULL,
    [Appointment Date]               DATETIME         NOT NULL,
    [Part Time %]                    DECIMAL (38, 20) NOT NULL,
    [End Date]                       DATETIME         NOT NULL,
    [Resignation Date]               DATETIME         NOT NULL,
    [Resignation Reason]             VARCHAR (20)     NOT NULL,
    [Contract Returned]              TINYINT          NOT NULL,
    [Notes]                          VARCHAR (100)    NOT NULL,
    [Experience]                     DECIMAL (38, 20) NOT NULL,
    [Grade Code Qualification]       VARCHAR (10)     NOT NULL,
    [Effective Date]                 DATETIME         NOT NULL,
    [Total]                          DECIMAL (38, 20) NOT NULL,
    [Grade Code Indicator]           VARCHAR (10)     NOT NULL,
    [Grade Code Letter]              VARCHAR (20)     NOT NULL,
    [Person Covered]                 VARCHAR (30)     NOT NULL,
    [Temporary Reason]               VARCHAR (160)    NOT NULL,
    [Group Range _ Level Integer]    INT              NOT NULL,
    [Curr_ Emp_ Continuous Service]  DATETIME         NOT NULL,
    [Local Gov_ Continuous Service]  DATETIME         NOT NULL,
    [Weeks Worked]                   INT              NOT NULL,
    [Days Worked]                    INT              NOT NULL,
    [Payroll Notes]                  VARCHAR (75)     NOT NULL,
    [Sick Pay Date]                  DATETIME         NOT NULL,
    [Modified By]                    VARCHAR (20)     NOT NULL,
    [Last Date Modified]             DATETIME         NOT NULL,
    [Perm_ Hours]                    DECIMAL (38, 20) NOT NULL,
    [Weeks]                          DECIMAL (38, 20) NOT NULL,
    [Date Increment Due]             DATETIME         NOT NULL,
    [Protected Salary]               TINYINT          NOT NULL,
    [Residential]                    TINYINT          NOT NULL,
    [Rent Amount Code]               VARCHAR (10)     NOT NULL,
    [Full _ Part Time]               INT              NOT NULL,
    [Full Time Hours]                DECIMAL (38, 20) NOT NULL,
    [Named Child]                    VARCHAR (60)     NOT NULL,
    [Territory Code]                 VARCHAR (10)     NOT NULL,
    [Temp_ Hours]                    DECIMAL (38, 20) NOT NULL,
    [Temp_ Hours End Date]           DATETIME         NOT NULL,
    [Total Hours]                    DECIMAL (38, 20) NOT NULL,
    [Upper Pay Spine]                DECIMAL (38, 20) NOT NULL,
    [Super Status]                   VARCHAR (10)     NOT NULL,
    [Grade Code]                     VARCHAR (30)     NOT NULL,
    [Hourly Rate]                    DECIMAL (38, 20) NOT NULL,
    [Daily Rate]                     DECIMAL (38, 20) NOT NULL,
    [Religious Instruction]          TINYINT          NOT NULL,
    [Pay Frequency]                  INT              NOT NULL,
    [Re Issued From]                 VARCHAR (20)     NOT NULL,
    [Re Issued To]                   VARCHAR (20)     NOT NULL,
    [Original Appointment]           VARCHAR (20)     NOT NULL,
    [Re Issue Reason]                VARCHAR (80)     NOT NULL,
    [Manual _ System End Date]       INT              NOT NULL,
    [Fixed Term Date]                DATETIME         NOT NULL,
    [Pay Notification Required]      TINYINT          NOT NULL,
    [Pay Notification Date Printed]  DATETIME         NOT NULL,
    [Budget Code 1]                  VARCHAR (12)     NOT NULL,
    [Budget Code 2]                  VARCHAR (12)     NOT NULL,
    [Budget Code 3]                  VARCHAR (12)     NOT NULL,
    [Budget Code 4]                  VARCHAR (12)     NOT NULL,
    [Budget Hours 1]                 DECIMAL (38, 20) NOT NULL,
    [Budget Hours 2]                 DECIMAL (38, 20) NOT NULL,
    [Budget Hours 3]                 DECIMAL (38, 20) NOT NULL,
    [Budget Hours 4]                 DECIMAL (38, 20) NOT NULL,
    [Budget % 1]                     DECIMAL (38, 20) NOT NULL,
    [Budget % 2]                     DECIMAL (38, 20) NOT NULL,
    [Budget % 3]                     DECIMAL (38, 20) NOT NULL,
    [Budget % 4]                     DECIMAL (38, 20) NOT NULL,
    [Pension 1]                      VARCHAR (20)     NOT NULL,
    [Pension 2]                      VARCHAR (20)     NOT NULL,
    [Pension 2 Amount]               DECIMAL (38, 20) NOT NULL,
    [Continuous Service Incr_ Due]   DATETIME         NOT NULL,
    [Basic Hourly Rate]              DECIMAL (38, 20) NOT NULL,
    [Basic Daily Rate]               DECIMAL (38, 20) NOT NULL,
    [Fast Track Points]              DECIMAL (38, 20) NOT NULL,
    [Discretionary Points]           DECIMAL (38, 20) NOT NULL,
    [Pension Form Required]          TINYINT          NOT NULL,
    [Pension Form Date Printed]      DATETIME         NOT NULL,
    [Police Check Authority]         VARCHAR (10)     NOT NULL,
    [Payment Received]               DECIMAL (38, 20) NOT NULL,
    [ID Card Sent]                   DATETIME         NOT NULL,
    [Date Cleared for Supply]        DATETIME         NOT NULL,
    [TAR Protected]                  TINYINT          NOT NULL,
    [Sept Assimilated Pay Scale]     TINYINT          NOT NULL,
    [Key Workers]                    TINYINT          NOT NULL,
    [Original Salary]                DECIMAL (38, 20) NOT NULL,
    [Safeguard 1 Amount]             DECIMAL (38, 20) NOT NULL,
    [Safeguard 1 End Date]           DATETIME         NOT NULL,
    [Safeguard 2 Amount]             DECIMAL (38, 20) NOT NULL,
    [Safeguard 2 End Date]           DATETIME         NOT NULL,
    [Safeguard 3 Amount]             DECIMAL (38, 20) NOT NULL,
    [Safeguard 3 End Date]           DATETIME         NOT NULL,
    [Safeguard 4 Amount]             DECIMAL (38, 20) NOT NULL,
    [Safeguard 4 End Date]           DATETIME         NOT NULL,
    [Safeguard Total]                DECIMAL (38, 20) NOT NULL,
    [TLR Description]                VARCHAR (50)     NOT NULL,
    [TLR Amount]                     DECIMAL (38, 20) NOT NULL,
    [TLR Difference]                 DECIMAL (38, 20) NOT NULL,
    [Original Point]                 DECIMAL (38, 20) NOT NULL,
    [TLR End Date]                   DATETIME         NOT NULL,
    [Safeguard Amount]               DECIMAL (38, 20) NOT NULL,
    [TLR Part Time]                  DECIMAL (38, 20) NOT NULL,
    [Safeguard 1 Part Time]          DECIMAL (38, 20) NOT NULL,
    [Safeguard 2 Part Time]          DECIMAL (38, 20) NOT NULL,
    [Safeguard 3 Part Time]          DECIMAL (38, 20) NOT NULL,
    [Safeguard 4 Part Time]          DECIMAL (38, 20) NOT NULL,
    [Safeguard PT Total]             DECIMAL (38, 20) NOT NULL,
    [Medical Status]                 INT              NOT NULL,
    [Medical Processed Date]         DATETIME         NOT NULL,
    [Medical 1st Reminder Due Date]  DATETIME         NOT NULL,
    [Occ Health Reminder Due Date]   DATETIME         NOT NULL,
    [Medical Comments]               VARCHAR (250)    NOT NULL,
    [Date School Notified]           DATETIME         NOT NULL,
    [Disability]                     TINYINT          NOT NULL,
    [OH Comments]                    VARCHAR (230)    NOT NULL,
    [Pensionable Contr_Salary]       DECIMAL (38, 20) NOT NULL,
    [Pensionable Contr_% Rate]       DECIMAL (38, 20) NOT NULL,
    [Opted out of LGPS]              DATETIME         NOT NULL,
    [Employer Pens_ Contr_% Rate]    DECIMAL (38, 20) NOT NULL,
    [Web Appointment Type]           INT              NOT NULL,
    [Contract Status Code]           VARCHAR (20)     NOT NULL,
    [Contract Additional Text Code]  VARCHAR (10)     NOT NULL,
    [Job Setup Title Code]           VARCHAR (20)     NOT NULL,
    [Scale Code]                     VARCHAR (20)     NOT NULL,
    [Basic Weeks per Year]           DECIMAL (38, 20) NOT NULL,
    [Entitlement Weeks]              DECIMAL (38, 20) NOT NULL,
    [Protected Weeks]                DECIMAL (38, 20) NOT NULL,
    [Job Family Code]                VARCHAR (30)     NOT NULL,
    [Job Setup Area]                 VARCHAR (10)     NOT NULL,
    [Pay Setup Area]                 VARCHAR (10)     NOT NULL,
    [Allowance Setup Area]           VARCHAR (10)     NOT NULL,
    [Weeks Setup Area]               VARCHAR (10)     NOT NULL,
    [Grade Setup Area]               VARCHAR (10)     NOT NULL,
    [Variance Setup Area]            VARCHAR (10)     NOT NULL,
    [Pay Calculation Method]         INT              NOT NULL,
    [Job Description]                VARCHAR (50)     NOT NULL,
    [Range Start Point Code]         VARCHAR (10)     NOT NULL,
    [Leadership Base Point]          INT              NOT NULL,
    [Contract Answer]                VARCHAR (30)     NOT NULL,
    [Point Code]                     VARCHAR (20)     NOT NULL,
    [Allowance Code 1]               VARCHAR (20)     NOT NULL,
    [Allowance Amount Type 1]        INT              NOT NULL,
    [Allowance Full Time Amount 1]   DECIMAL (38, 20) NOT NULL,
    [Allowance Part Time Amount 1]   DECIMAL (38, 20) NOT NULL,
    [Allowance End Date 1]           DATETIME         NOT NULL,
    [Allowance Code 2]               VARCHAR (20)     NOT NULL,
    [Allowance Amount Type 2]        INT              NOT NULL,
    [Allowance Full Time Amount 2]   DECIMAL (38, 20) NOT NULL,
    [Allowance Part Time Amount 2]   DECIMAL (38, 20) NOT NULL,
    [Allowance End Date 2]           DATETIME         NOT NULL,
    [Allowance Code 3]               VARCHAR (20)     NOT NULL,
    [Allowance Amount Type 3]        INT              NOT NULL,
    [Allowance Full Time Amount 3]   DECIMAL (38, 20) NOT NULL,
    [Allowance Part Time Amount 3]   DECIMAL (38, 20) NOT NULL,
    [Allowance End Date 3]           DATETIME         NOT NULL,
    [Allowance Code 4]               VARCHAR (20)     NOT NULL,
    [Allowance Amount Type 4]        INT              NOT NULL,
    [Allowance Full Time Amount 4]   DECIMAL (38, 20) NOT NULL,
    [Allowance Part Time Amount 4]   DECIMAL (38, 20) NOT NULL,
    [Allowance End Date 4]           DATETIME         NOT NULL,
    [Salary Full Time]               DECIMAL (38, 20) NOT NULL,
    [Salary Part Time]               DECIMAL (38, 20) NOT NULL,
    [Salary Incl_ Allowances]        DECIMAL (38, 20) NOT NULL,
    [Sal_ Inc_ Allw_ Inc_ Hrly Rate] DECIMAL (38, 20) NOT NULL,
    [Protected Weeks Notes]          VARCHAR (100)    NOT NULL,
    [Original Pre Oyster Weeks]      DECIMAL (38, 20) NOT NULL,
    [Exclude From Migration Report]  TINYINT          NOT NULL,
    [Protected Weeks Reissue]        TINYINT          NOT NULL,
    [Full Time Weeks]                DECIMAL (38, 20) NOT NULL,
    [Supply Appointment]             VARCHAR (20)     NOT NULL,
    [Created from Dataport]          TINYINT          NOT NULL,
    [TPS Change]                     TINYINT          NOT NULL,
    [On Maternity]                   TINYINT          NOT NULL,
    [TPS Opt Out Date]               DATETIME         NOT NULL,
    [Pension Notes]                  VARCHAR (100)    NOT NULL,
    [LGPS Reduced Pay]               TINYINT          NOT NULL,
    [Earnings Over Threshold]        TINYINT          NOT NULL,
    [MAT Contract Start Date]        DATETIME         NOT NULL,
    [Fast Portal Submitted]          TINYINT          NOT NULL,
    [Federation Trust]               VARCHAR (20)     NOT NULL,
    [Employee Surname]               VARCHAR (50)     NOT NULL,
    [Support Assessment Form Reqd]   TINYINT          NOT NULL,
    [Support Assessment Form Sent]   DATETIME         NOT NULL,
    [Linked PAYE ?]                  TINYINT          NOT NULL,
    [Linked PAYE School]             VARCHAR (20)     NOT NULL,
    [Linked PAYE Appointment]        VARCHAR (20)     NOT NULL,
    [Linked PAYE Disposition]        INT              NOT NULL,
    [PA Support Assess Approved]     TINYINT          NOT NULL,
    [PT Incl_ Pens_ Allowances]      DECIMAL (38, 20) NOT NULL,
    [FT Incl_ Pens_ Allowances]      DECIMAL (38, 20) NOT NULL,
    [Pension 3]                      VARCHAR (20)     NOT NULL,
    [Pension 3 Amount]               DECIMAL (38, 20) NOT NULL,
    [Pension 4]                      VARCHAR (20)     NOT NULL,
    [Pension 4 Amount]               DECIMAL (38, 20) NOT NULL,
    [Comments]                       VARCHAR (100)    NOT NULL,
    [Date Joined LGPS]               DATETIME         NOT NULL,
    [TPS School No_]                 VARCHAR (10)     NOT NULL,
    [Leave Type]                     INT              NOT NULL,
    [LGPS Fund]                      VARCHAR (30)     NOT NULL,
    [LGPS Membership No_]            VARCHAR (20)     NOT NULL,
    CONSTRAINT [EPM$Appointment$0] PRIMARY KEY CLUSTERED ([No_] ASC) WITH (FILLFACTOR = 99)
);

